package biometricsecurity.view;

import biometricsecurity.controller.MainController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Supun
 */
public class KeyStrokeTrain extends javax.swing.JFrame {

    private MainController controller;
    private int count;
    private boolean complete;
    
    /**
     * Creates new form KeyStrokeTrain
     * @param controller
     */
    public KeyStrokeTrain(MainController controller, String userName) {
        initComponents();
        errorLbl.setVisible(false);
        count = 0;
        this.controller = controller;
        // Center the view
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (dim.width/2-this.getSize().getWidth()/2), (int) (dim.height/2 - this.getSize().getHeight()/2));
        
        userNameLbl.setText("User Name : " + userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLbl = new javax.swing.JLabel();
        trainBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        errorLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Train Key Stroke Dynamics");

        userNameLbl.setText("User Name : ");

        trainBtn.setText("Train Model");
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setText("Training of the model is completed. Please click on the submit button to complete.");

        errorLbl1.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl1.setText("Please train the model many times to have an accurate login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(userNameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(trainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorLbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(userNameLbl)
                .addGap(23, 23, 23)
                .addComponent(errorLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(trainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLbl)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed
        if (count == 10){
            JOptionPane.showMessageDialog(this, "Training the model is completed. Now press submit to complete.", "Training Complete", JOptionPane.ERROR_MESSAGE);
            return;
        }
        KeyStrokeTrainDialog kDialog = new KeyStrokeTrainDialog(this, true, controller, controller.getSentence(count));
        kDialog.setVisible(true);
        
        count ++;
        if(count==10){
            errorLbl.setVisible(true);
        }
        
        complete = true;
    }//GEN-LAST:event_trainBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (!complete){
            JOptionPane.showConfirmDialog(this, "You have to train the model at least one time.", "Not enough data", JOptionPane.ERROR_MESSAGE);
            return ;
            
        }
        
        controller.saveKeyStrokeUser();
        JOptionPane.showMessageDialog(this, "Create new account completed. You may now sign in.", "Account Created Successfully", JOptionPane.INFORMATION_MESSAGE);
        
        SignInFrame sIFrame = new SignInFrame(controller);
        sIFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel errorLbl1;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton trainBtn;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables
}
