/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricsecurity.view;

import biometricsecurity.controller.MainController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Supun
 */
public class KeyStrokeSignIn extends javax.swing.JFrame {

    private MainController controller;
    private String sentence;
    
    // Current position of the sentence
    private int currentPos;
    private long lastTime;
    private double[] times;
    
    String userName;
    
    
    public KeyStrokeSignIn(MainController controller, String userName) {
        initComponents();
        
        currentPos = 0;
        sentence = controller.getAuthSentene();
        times = new double[sentence.length()];
        this.controller = controller;
        
        errorLbl.setVisible(false);
        txtLbl.setText("");
        sentenceLbl.setText(sentence);
        this.userName = userName;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (dim.width/2-this.getSize().getWidth()/2), (int) (dim.height/2 - this.getSize().getHeight()/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        btnRetry = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        txtLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sentenceLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnRetry.setText("Retry");
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });

        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setText("Please click submit button to submit the results. Or press retry.");

        txtLbl.setForeground(new java.awt.Color(255, 0, 0));
        txtLbl.setText("Text");

        jLabel1.setText("Type the following sentence using your usual typing speed");

        sentenceLbl.setText("<<Sentence>>");

        txtInput.setColumns(20);
        txtInput.setRows(5);
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtInput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRetry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sentenceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(errorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sentenceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnRetry, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (currentPos < sentence.length()){
            JOptionPane.showMessageDialog(this, "Please complete the whole sentence", "Incomplete Sentence", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (controller.validateKeyStrokeAuth(userName, sentence, times)){
            JOptionPane.showMessageDialog(this, "Login Successful.", "Login Success", JOptionPane.INFORMATION_MESSAGE);
            LoginSuccess lSFrame = new LoginSuccess();
            lSFrame.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "There's a significant change in typing speed. Please try again.", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed
        currentPos = 0;
        txtInput.setText("");
        txtLbl.setText("");
        errorLbl.setVisible(false);
    }//GEN-LAST:event_btnRetryActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        if (currentPos == sentence.length()){
            txtInput.setText("");
            return;
        }

        if (evt.getKeyChar() == sentence.charAt(currentPos)){
            if (currentPos == 0){
                lastTime = System.currentTimeMillis();
                currentPos ++;
            }else{
                times[currentPos-1] = System.currentTimeMillis() - lastTime;
                lastTime = System.currentTimeMillis();
                currentPos++;
            }
            txtLbl.setText(sentence.substring(0, currentPos));
        }

        if (currentPos == sentence.length()){
            JOptionPane.showMessageDialog(this, "Data successfully recorded.", "Success", JOptionPane.INFORMATION_MESSAGE);
            errorLbl.setVisible(true);
            return;
        }
    }//GEN-LAST:event_txtInputKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetry;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sentenceLbl;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JLabel txtLbl;
    // End of variables declaration//GEN-END:variables
}
